print("Co gang hoc lap trinh tot - nhung dao duc phai tot nua")
print("\"Vi tuong lai\"")
print("\'Tat ca co len\'")
print("")
print("Ghi nho cac ky tu va lenh dac biet:")
print("\\n - xuong hang")
print("endl - xuong hang")
print("\\t - tab",end='')